# Web

version: '2'

services:
 web:
   container_name: nodejs-hapijs
   image: douglaszuqueto/alpine-nodejs:6.3.0
   volumes:
    - .:/app
   working_dir: /app
   command: npm start
   ports:
    - 3000:3000
